### ISSUE TITLE
[Beginner] Create Django Model for Blog Posts

### ISSUE THREAD

**Issue by Imadnajam** [UnderLions/-React-Learning-Django#1]
Set up a Django model for blog posts, including fields for title, content, and publication date.

**Comment by VidyaYadavv1519** [comment]
hiii, can you assign me this issue ??

**Comment by Imadnajam** [comment]
> hiii, can you assign me this issue ??
yes sure

**Comment by VidyaYadavv1519** [comment]
hey, there are two apps leads and frontend in which app do you want this model

**Comment by Imadnajam** [comment]
it's a good practice to keep related models together within a single app. In this case, you might consider creating a new app specifically for handling blog-related functionality. Let's call this app _**### blog**_.
